linters-settings:
  gosimple:
    checks: [ "all" ]
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    checks: [ "all" ]
  revive:
    ignore-generated-header: true
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: false
        arguments:
          - maxLitCount: "3"
            allowInts: "0,1"
      - name: argument-limit
        arguments: [ 4 ]
      - name: banned-characters
        severity: warning
        disabled: false
        arguments: ["Ω", "Σ", "σ", "7"]
      - name: cognitive-complexity
        arguments: [ 9 ]
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T"
      - name: cyclomatic
        arguments: [ 7 ]
      - name: defer
        arguments:
          - [ "call-chain", "loop" ]
      - name: file-header
        disabled: true
      - name: function-result-limit
        arguments: [ 3 ] #3 TODO
      - name: flag-parameter
        disabled: true #4 TODO
      - name: function-length
        disabled: false
        arguments: [ 10, 20 ]
      - name: line-length-limit
        arguments: [ 120 ]
      - name: max-public-structs
        arguments: [ 3 ]
      - name: string-format
        arguments:
          - - 'core.WriteError[1].Message'
            - '/^([^A-Z]|$)/'
            - must not start with a capital letter
          - - 'fmt.Errorf[0]'
            - '/(^|[^\.!?])$/'
            - must not end in punctuation
          - - panic
            - '/^[^\n]*$/'
            - must not contain line breaks
      - name: unhandled-error
        arguments:
          - "fmt.Printf"
  stylecheck:
    checks: [ "all" ]
  gosec:
    exclude-generated: true
    severity: high
    concurrency: 3
  gocritic:
    enabled-checks:
      - hugeParam
      - tooManyResultsChecker
      - rangeValCopy
      - rangeExprCopy
      - nestingReduce
      - unnamedResult
      - truncateCmp
      - ruleguard
      - elseif
      - captLocal
      - underef
    settings:
      captLocal:
        paramsOnly: false
      elseif:
        skipBalanced: false
      hugeParam:
        sizeThreshold: 256
      truncateCmp:
        skipArchDependent: false
      underef:
        skipRecvDeref: false
      unnamedResult:
        checkExported: true
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - stylecheck
    - gosec
    - gocritic
issues:
  # See the dedicated "issues" documentation section.
  exclude-rules:
    - path: _test\.go
      text: "add-constant:"
    - path: _test\.go
      text: "line-length-limit:"
    - path: _test\.go
      text: "function-length: maximum number of lines"
    - path: _test\.go
      text: "function-length: maximum number of statements"
    - path: '(.*)\/index\.go'
      text: "function-length: maximum number of statements"